"""Deterministic layer: sources in ``knowledge/`` become Markdown with page anchors plus an index.

Incremental by content hash: a source is reconverted only when its bytes change.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

KNOWLEDGE_DIR = "knowledge"
STATE_DIR = Path(".covener") / "knowledge"
STATE_FILE = "state.json"
INDEX_FILE = "INDEX.md"
CITATIONS_FILE = "CITATIONS.md"
SOURCE_SUFFIXES: frozenset[str] = frozenset({".pdf", ".md", ".txt"})
GENERATED_MARK = "<!-- generated by covener knowledge; edit the source, not this file -->"
PAGE_HEADING_RE = re.compile(r"^## Page (\d+)\s*$")


@dataclass
class Document:
    """A converted source: Markdown text with ``## Page N`` headings."""

    id: str  # path under knowledge/ without suffix, posix
    source: str  # repository-relative source path
    markdown: str  # repository-relative converted path (same as source for .md/.txt)
    title: str
    pages: int
    sha256: str
    text: str = ""

    def anchor(self, page: int) -> str:
        return f"{self.markdown}#page-{page}"


@dataclass
class BuildReport:
    converted: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    documents: list[Document] = field(default_factory=list)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 16), b""):
            digest.update(block)
    return digest.hexdigest()


def _title_from_text(text: str, fallback: str) -> str:
    for line in text.splitlines():
        stripped = line.strip().lstrip("#").strip()
        if len(stripped) >= 4 and not stripped.startswith("<!--") and not PAGE_HEADING_RE.match(line.strip()):
            return stripped[:120]
    return fallback


def pdf_to_markdown(path: Path, title: str) -> tuple[str, int]:
    """Extract text page by page. Requires ``pypdf`` (``pip install covener[knowledge]``)."""
    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise RuntimeError("PDF conversion needs pypdf: pip install 'covener[knowledge]'") from exc
    reader = PdfReader(str(path))
    parts = [GENERATED_MARK, f"# {title}", ""]
    for number, page in enumerate(reader.pages, start=1):
        text = (page.extract_text() or "").strip()
        parts += [f"## Page {number}", "", text, ""]
    return "\n".join(parts).rstrip() + "\n", len(reader.pages)


def _pages_in(text: str) -> int:
    numbers = [int(m.group(1)) for m in (PAGE_HEADING_RE.match(line.strip()) for line in text.splitlines()) if m]
    return max(numbers) if numbers else 1


def _sources(knowledge_dir: Path) -> list[Path]:
    if not knowledge_dir.is_dir():
        return []
    result = []
    for path in sorted(knowledge_dir.rglob("*")):
        rel = path.relative_to(knowledge_dir)
        if not path.is_file() or any(part.startswith(".") for part in rel.parts):
            continue
        if path.suffix.lower() not in SOURCE_SUFFIXES or path.name in {INDEX_FILE, CITATIONS_FILE}:
            continue
        if path.suffix.lower() == ".md":
            try:
                if path.read_text(encoding="utf-8", errors="ignore").startswith(GENERATED_MARK):
                    continue  # our own output next to a PDF
            except OSError:
                continue
        result.append(path)
    return result


def load_state(root: Path) -> dict[str, dict[str, str]]:
    path = root / STATE_DIR / STATE_FILE
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return data.get("sources", {}) if isinstance(data, dict) else {}


def save_state(root: Path, sources: dict[str, dict[str, str]]) -> None:
    path = root / STATE_DIR / STATE_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"version": 1, "sources": sources}, indent=2) + "\n", encoding="utf-8")


def build_documents(root: Path, dry_run: bool = False) -> BuildReport:
    """Convert new or changed sources, drop outputs of deleted sources, return every document."""
    knowledge_dir = root / KNOWLEDGE_DIR
    report = BuildReport()
    previous = load_state(root)
    current: dict[str, dict[str, str]] = {}
    for source in _sources(knowledge_dir):
        rel = source.relative_to(root).as_posix()
        doc_id = source.relative_to(knowledge_dir).with_suffix("").as_posix()
        digest = _sha256(source)
        if source.suffix.lower() == ".pdf":
            markdown_path = source.with_suffix(".md")
            markdown_rel = markdown_path.relative_to(root).as_posix()
            if previous.get(rel, {}).get("sha256") == digest and markdown_path.is_file():
                report.unchanged.append(rel)
                text = markdown_path.read_text(encoding="utf-8")
            else:
                title = source.stem.replace("-", " ").replace("_", " ")
                try:
                    text, _ = pdf_to_markdown(source, title)
                except RuntimeError as exc:
                    report.skipped.append(rel)
                    report.notes.append(str(exc))
                    continue
                if not dry_run:
                    markdown_path.write_text(text, encoding="utf-8")
                report.converted.append(markdown_rel)
        else:
            markdown_rel = rel
            text = source.read_text(encoding="utf-8", errors="replace")
            (report.unchanged if previous.get(rel, {}).get("sha256") == digest else report.converted).append(rel)
        pages = _pages_in(text)
        document = Document(
            id=doc_id,
            source=rel,
            markdown=markdown_rel,
            title=_title_from_text(text, doc_id),
            pages=pages,
            sha256=digest,
            text=text,
        )
        report.documents.append(document)
        current[rel] = {"sha256": digest, "markdown": markdown_rel}
    for rel, info in previous.items():
        if rel not in current:
            report.removed.append(rel)
            generated = root / info.get("markdown", "")
            if not dry_run and info.get("markdown") != rel and generated.is_file():
                try:
                    if generated.read_text(encoding="utf-8", errors="ignore").startswith(GENERATED_MARK):
                        generated.unlink()
                except OSError:
                    pass
    if not dry_run:
        save_state(root, current)
    return report


def render_index(documents: list[Document]) -> str:
    lines = [
        GENERATED_MARK,
        "# Knowledge index",
        "",
        f"{len(documents)} documents, updated {date.today().isoformat()}. Cite a page as `<file>#page-<n>`.",
        "",
        "| Id | Title | Pages | Source |",
        "|---|---|---|---|",
    ]
    for doc in documents:
        lines.append(f"| {doc.id} | {doc.title} | {doc.pages} | {doc.source} |")
    return "\n".join(lines) + "\n"
